import random

verbs = [
    'batter',
    'bang',
    'bludgeon',
    'break',
    'burst',
    'clash',
    'crack',
    'crash',
    'crunch',
    'crush',
    'cut',
    'destroy',
    'dislocate',
    'drive',
    'eviscerate',
    'grind',
    'impale',
    'jab',
    'kick',
    'open',
    'pound',
    'pierce',
    'pulverize',
    'pummel',
    'punch',
    'puncture',
    'rake',
    'rip',
    'scrape',
    'sever',
    'shatter',
    'skewer',
    'slam',
    'slice',
    'skin',
    'slash',
    'smack',
    'splinter',
    'split',
    'stab',
    'strike',
    'tear',
    'thrust',
    'wrench'
]

locations = [
    'abdomen',
    'arm',
    'brain',
    'chest',
    'collarbone',
    'ear',
    'elbow',
    'eye socket',
    'face',
    'femur',
    'forearm',
    'groin',
    'head',
    'intestine',
    'kidney',
    'jaw',
    'lung',
    'neck',
    'nose',
    'pelvis',
    'ribs',
    'shin',
    'skull',
    'spine',
    'spleen',
    'stomach',
    'thigh',
    'throat',
    'torso'
]

effects = [
    'arterial spray',
    'blood curdling shriek',
    'bouncing head',
    'crumpled on the floor',
    'cut in two',
    'clutching entrails',
    'exploding into mist',
    'disembowel',
    'dislocating the arm',
    'flopping on the floor',
    'flying across the room',
    'gasping for breath',
    'gouts of blood',
    'gurgling',
    'mass of pulpy tissue',
    'screaming in pain',
    'sickening crunch',
    'shattering ribs',
    'spraying teeth',
    'splashing blood',
    'twitching',
    'vomiting blood'
]

print(f'Verb: {random.choice(verbs)}')
print(f'Location: {random.choice(locations)}')
print(f'Effects: {random.choice(effects)}')
